[information]
name = "onehalf"
background = "dark"
author = 'Roan Mason <roanmason@live.ca>'

[palette]

black = '#282c34'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#dcdfe4'
fg = '#dcdfe4'
bg = '#282c34'

light_black = '#383a42'
light_red = '#e45649'
light_green = '#50a14f'
light_yellow = '#c18401'
light_blue = '#0184bc'
light_magenta = '#a626a4'
light_cyan = '#0997b3'
light_white = '#fafafa'
light_fg = '#383a42'
light_bg = '#fafafa'


comment_fg = '#5c6370'
gutter_bg = 'bg'
gutter_fg = '#919baa'
non_text = '#373C45'

cursor_line = '#313640'
color_col = '#313640'

selection = '#474e5d'
vertsplit = '#313640'


# group = 'foreground background style special blend'

[highlights]
# User Interface Colors
Normal = 'fg bg'
NormalFloat = 'comment_fg bg'
# FloatBorder = 'fg bg'

Pmenu = 'comment_fg bg'
PmenuSel = '- selection'
PmenuKind = 'link:Pmenu'
PmenuKindSel = 'link:PmenuSel'
PmenuExtra = 'link:Pmenu'
PmenuExtraSel = 'link:PmenuSel'
PmenuSbar = 'selection'
PmenuThumb = 'fg'


Cursor = 'bg blue'
CursorColumn = '- cursor_line'
CursorLine = '- cursor_line'

LineNr = 'gutter_fg gutter_bg'
CursorLineNr = 'fg'

DiffAdd = 'green'
DiffChange = 'yellow'
DiffDelete = 'red'
DiffText = 'blue'

IncSearch = 'bg yellow'
Search = 'bg yellow'

ErrorMsg = 'fg'
ModeMsg = 'fg'
MoreMsg = 'fg'
WarningMsg = 'red'
Question = 'magenta'


SpellBad = 'red'
SpellCap = 'yellow'
SpellLocal = 'yellow'
SpellRare = 'yellow'

TabLine = 'comment_fg cursor_line'
TabLineFill = 'comment_fg cursor_line'
TabLineSel = 'fg bg'

Visual = '- selection'
VisualNOS = '- selection'

ColorColumn = '- color_col'
Conceal = 'fg'
Directory = 'blue'
VertSplit = 'vertsplit vertsplit'
Folded = 'fg'
FoldColumn = 'fg'
SignColumn = 'fg'

MatchParen = 'fg - u'
SpecialKey = 'fg'
Title = 'green'
WildMenu = 'fg'

# Added by ClearAspect


# highlights

Whitespace = 'non_text'
NonText = 'non_text'
Comment = 'comment_fg - i'
Constant = 'cyan'
String = 'green'
Character = 'green'
Number = 'yellow'
Boolean = 'yellow'
Float = 'yellow'

Identifier = 'red'
Function = 'blue'
Statement = 'magenta'

Conditional = 'magenta'
Repeat = 'magenta'
Label = 'magenta'
Operator = 'fg'
Keyword = 'red'
Exception = 'magenta'

PreProc = 'yellow'
Include = 'magenta'
Define = 'magenta'
Macro = 'magenta'
PreCondit = 'yellow'

Type = 'yellow'
StorageClass = 'yellow'
Structure = 'yellow'
Typedef = 'yellow'

Special = 'comment_fg'
SpecialChar = 'fg'
Tag = 'fg'
Delimiter = 'comment_fg'
SpecialComment = 'fg'
Debug = 'fg'
Underlined = 'fg'
Ignore = 'fg'
Error = 'red gutter_bg'
Todo = 'magenta'

# Added by ClearAspect

Variable = 'red'

Bold = '- - b'
Italic = '- - i'

# Old

# MsgArea = 'fg bg'
# MsgSeparator = 'fg bg'
# NormalNC = 'fg bg'
# QuickFixLine = '- blue'
# MatchWord = '- - u'
# MatchWordCur = '- - u'
# MatchParenCur = '- - u'
# lCursor = 'cursor_fg cursor_bg'
# CursorIM = 'cursor_fg cursor_bg'
# TermCursor = 'cursor_fg cursor_bg'
# TermCursorNC = 'cursor_fg cursor_bg'
# Substitute = 'light_black light_red'
# EndOfBuffer = 'bg'

[Treesitter]

# Links to highlight groups

TSText = 'fg'

TSComment = 'link:Comment'
TSConstant = 'link:Constant'
TSConstMacro = 'link:Constant'
TSString = 'link:String'
TSStringRegex = 'link:String'
TSStringEscape = 'link:String'
TSCharacter = 'link:Character'
TSNumber = 'link:Number'
TSBoolean = 'link:Boolean'
TSFloat = 'link:Float'

TSFunction = 'link:Function'
TSFuncBuiltin = 'link:Function'
TSFuncMacro = 'link:Function'
TSMethod = 'link:Function'

TSConditional = 'link:Conditional'
TSRepeat = 'link:Repeat'
TSLabel = 'link:Label'
TSOperator = 'link:Operator'
TSKeyword = 'link:Keyword'
TSKeywordReturn = 'link:Keyword'
TSKeywordFunction = 'link:Keyword'
TSException = 'link:Exception'

TSInclude = 'link:Include'

TSType = 'link:Type'
TSTypeBuiltin = 'link:Type'
TSStructure = 'link:Structure'

TSPunctSpecial = 'link:Special'

TSTag = 'link:Tag'
TSPunctDelimiter = 'link:Delimiter'
TSUnderline = 'link:Underlined'
TSError = 'link:Error'


TSVariable = 'link:Variable'
TSVariableBuiltin = 'link:Variable'


# Custom highlights

# TSTagDelimiter = 'link:Delimiter'
# TSTagAttribute = 'link:Tag'
# TSAnnotation = 'blue'
# TSAttribute = 'cyan'
# TSConstructor = 'cyan'
# TSNamespace = 'cyan'
# TSConstBuiltin = 'light_red'
# TSProperty = 'red'
# TSField = 'fg'
# TSParameter = 'red'
# TSParameterReference = 'red'
# TSSymbol = 'blue'
# TSPunctBracket = 'fg -'
# TSEmphasis = '- - i'
# TSTitle = 'fg - -'
# TSLiteral = 'light_red'
# TSURI = 'light_red - u'
# TSKeywordOperator = 'magenta'
# TSStrong = 'blue - b'
# TSQueryLinterError = 'light_red'
# TreesitterContext = '- light_black'

# [markdown]
# markdownBlockquote = 'green'
# markdownCode = 'light_red'
# markdownCodeBlock = 'light_red'
# markdownCodeDelimiter = 'light_red'
# markdownH1 = 'blue'
# markdownH2 = 'blue'
# markdownH3 = 'blue'
# markdownH4 = 'blue'
# markdownH5 = 'blue'
# markdownH6 = 'blue'
# markdownHeadingDelimiter = 'blue'
# markdownHeadingRule = 'fg - b'
# markdownId = 'magenta'
# markdownIdDeclaration = 'blue'
# markdownIdDelimiter = 'light_black'
# markdownLinkDelimiter = 'light_black'
# markdownBold = 'blue - b'
# markdownItalic = '- - i'
# markdownBoldItalic = 'yellow - bi'
# markdownListMarker = 'blue'
# markdownOrderedListMarker = 'blue'
# markdownRule = 'light_black'
# markdownUrl = 'cyan - u'
# markdownLinkText = 'blue'
# markdownFootnote = 'light_red'
# markdownFootnoteDefinition = 'light_red'
# markdownEscape = 'yellow'

[Whichkey] # Done
WhichKey = 'red bg'
WhichKeyBorder = 'fg bg'
WhichKeyDesc = 'blue'
WhichKeyGroup = 'yellow'
WhichKeyIcon = 'fg'
WhichKeyNormal = 'red bg'
WhichKeySeparator = 'green'
WhichKeyTitle = 'blue'
WhichKeyValue = 'green'


[Git]
GitSignsAdd = 'green'
GitSignsAddNr = 'green'    # Number column signs
GitSignsAddLn = '- green'  # Line highlights
GitSignsAddCul = '- green' # Current line highlights

GitSignsChange = 'yellow'
GitSignsChangeNr = 'yellow'
GitSignsChangeLn = '- yellow'
GitSignsChangeCul = '- yellow'

GitSignsDelete = 'red'
GitSignsDeleteNr = 'red'
GitSignsDeleteLn = '- red'
GitSignsDeleteCul = '- red'


# [LSP]
# LspDiagnosticsDefaultError = 'red'
# LspDiagnosticsDefaultWarning = 'light_red'
# LspDiagnosticsDefaultInformation = 'yellow'
# LspDiagnosticsDefaultInfo = 'yellow'
# LspDiagnosticsDefaultHint = 'blue'
# LspDiagnosticsVirtualTextError = 'red'
# LspDiagnosticsVirtualTextWarning = 'light_red'
# LspDiagnosticsVirtualTextInformation = 'yellow'
# LspDiagnosticsVirtualTextInfo = 'yellow'
# LspDiagnosticsVirtualTextHint = 'blue'
# LspDiagnosticsFloatingError = 'red'
# LspDiagnosticsFloatingWarning = 'light_red'
# LspDiagnosticsFloatingInformation = 'yellow'
# LspDiagnosticsFloatingInfo = 'yellow'
# LspDiagnosticsFloatingHint = 'blue'
# DiagnosticSignError = 'red'
# DiagnosticSignWarning = 'light_red'
# DiagnosticSignInformation = 'yellow'
# DiagnosticSignInfo = 'yellow'
# DiagnosticSignHint = 'blue'
# LspDiagnosticsSignError = 'red'
# LspDiagnosticsSignWarning = 'light_red'
# LspDiagnosticsSignInformation = 'yellow'
# LspDiagnosticsSignInfo = 'yellow'
# LspDiagnosticsSignHint = 'blue'
# LspDiagnosticsError = 'red'
# LspDiagnosticsWarning = 'light_red'
# LspDiagnosticsInformation = 'yellow'
# LspDiagnosticsInfo = 'yellow'
# LspDiagnosticsHint = 'blue'
# LspDiagnosticsUnderlineError = '- - u'
# LspDiagnosticsUnderlineWarning = '- - u'
# LspDiagnosticsUnderlineInformation = '- - u'
# LspDiagnosticsUnderlineInfo = '- - u'
# LspDiagnosticsUnderlineHint = '- - u'
# LspReferenceRead = '- light_black'
# LspReferenceText = '- light_black'
# LspReferenceWrite = '- light_black'
# LspCodeLens = 'light_black - i'
# LspCodeLensSeparator = 'light_black - i'

[Telescope]
TelescopeSelection = 'blue'
TelescopeMatching = 'yellow - b'
TelescopeBorder = 'blue bg'

# [NvimTree]
# NvimTreeFolderIcon = 'blue'
# NvimTreeIndentMarker = 'light_black'
# NvimTreeNormal = 'light_black light_black'
# NvimTreeVertSplit = 'bg bg'
# NvimTreeFolderName = 'blue'
# NvimTreeOpenedFolderName = 'blue - bi'
# NvimTreeEmptyFolderName = 'light_black - i'
# NvimTreeGitIgnored = 'light_black - i'
# NvimTreeImageFile = 'light_black'
# NvimTreeSpecialFile = 'light_red'
# NvimTreeEndOfBuffer = 'light_black'
# NvimTreeCursorLine = 'black'
# NvimTreeGitignoreIcon = 'light_red'
# NvimTreeGitStaged = 'tree_sign_add'
# NvimTreeGitNew = 'tree_sign_add'
# NvimTreeGitRenamed = 'tree_sign_add'
# NvimTreeGitDeleted = 'sign_delete'
# NvimTreeGitMerge = 'tree_sign_change'
# NvimTreeGitDirty = 'tree_sign_change'

# NvimTreeSymlink = 'cyan'
# NvimTreeRootFolder = 'fg - b'
# NvimTreeExecFile = 'green'

# [Buffer]
# BufferCurrent = 'fg bg'
# BufferCurrentIndex = 'fg bg'
# BufferCurrentMod = 'yellow bg'
# BufferCurrentSign = 'blue bg'
# BufferCurrentTarget = 'red bg b'

# BufferVisible = 'fg bg'
# BufferVisibleIndex = 'fg bg'
# BufferVisibleMod = 'yellow bg'
# BufferVisibleSign = 'light_black bg'
# BufferVisibleTarget = 'red bg b'

# BufferInactive = 'light_black bg'
# BufferInactiveIndex = 'light_black bg'
# BufferInactiveMod = 'yellow bg'
# BufferInactiveSign = 'light_black bg'
# BufferInactiveTarget = 'red bg b'

[StatusLine]
StatusLine = 'blue cursor_line'
StatusLineNC = 'comment_fg cursor_line'

StatusLineSeparator = 'black'
StatusLineTerm = 'black'
StatusLineTermNC = 'black'

# [IndentBlankline]
# IndentBlanklineContextChar = 'light_black'
# IndentBlanklineContextStart = '- - u'
# IndentBlanklineChar = 'light_black'
# IndentBlanklineSpaceChar = 'cyan'
# IndentBlanklineSpaceCharBlankline = 'yellow'

# [Dashboard]
# DashboardHeader = 'blue'
# DashboardCenter = 'magenta'
# DashboardFooter = 'cyan'

[Cmp]
CmpItemAbbr = 'fg'
CmpItemAbbrDeprecated = 'comment_fg - s'
CmpItemAbbrMatch = 'fg'
CmpItemAbbrMatchFuzzy = 'fg'

CmpItemKind = 'fg'

CmpItemKindSnippet = 'magenta'
CmpItemKindCopilot = 'fg'
CmpItemKindFolder = 'blue'

CmpItemKindKeyword = 'link:Keyword'

CmpItemKindClass = 'link:Structure'
CmpItemKindInterface = 'link:Structure'
CmpItemKindStruct = 'link:Structure'
CmpItemKindEnum = 'link:Structure'

CmpItemKindConstructor = 'link:Special'

CmpItemKindFunction = 'link:Function'
CmpItemKindMethod = 'link:Function'

CmpItemKindVariable = 'link:Variable'
CmpItemKindField = 'link:Variable'
CmpItemKindProperty = 'link:Variable'
CmpItemKindText = 'link:Variable'

CmpItemKindEnumMember = 'link:Constant'
CmpItemKindConstant = 'link:Constant'

CmpItemKindEvent = 'fg'
CmpItemKindModule = 'fg'
CmpItemKindValue = 'fg'
CmpItemKindUnit = 'fg'
CmpItemKindFile = 'fg'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'fg'
CmpItemKindOperator = 'fg'
CmpItemKindTypeParameter = 'fg'


# [Blink] # Most link to CMP
# BlinkCmpMenu = 'fg bg'
# BlinkCmpMenuBorder = 'comment_fg bg'
# BlinkCmpMenuSelection = '-'
# BlinkCmpScrollBarThumb = '-'
# BlinkCmpScrollBarGutter = '-'
# BlinkCmpLabel = '-'
# BlinkCmpLabelMatch = '-'
# BlinkCmpLabelDeprecated = '-'
# BlinkCmpLabelDetail = '-'
# BlinkCmpLabelDescription = '-'
# BlinkCmpSource = '-'
# BlinkCmpGhostText = 'comment_fg'
# BlinkCmpDoc = '-'
# BlinkCmpDocBorder = '-'
# BlinkCmpDocSeparator = '-'
# BlinkCmpDocCursorLine = '-'
# BlinkCmpSignatureHelp = '-'
# BlinkCmpSignatureHelpBorder = '-'
# BlinkCmpSignatureHelpActiveParameter = '-'

# BlinkCmpKind = '-'

# BlinkCmpKindText = '-'
# BlinkCmpKindMethod = 'link:Function'
# BlinkCmpKindFunction = 'link:Function'
# BlinkCmpKindConstructor = 'link:Special'
# BlinkCmpKindField = 'link:Variable'
# BlinkCmpKindVariable = 'link:Variable'
# BlinkCmpKindClass = 'link:Structure'
# BlinkCmpKindInterface = 'link:Structure'
# BlinkCmpKindModule = 'link:Structure'
# BlinkCmpKindProperty = 'link:identifier'
# BlinkCmpKindUnit = '-'
# BlinkCmpKindValue = '-'
# BlinkCmpKindEnum = '-'
# BlinkCmpKindKeyword = '-'
# BlinkCmpKindSnippet = '-'
# BlinkCmpKindColor = '-'
# BlinkCmpKindFile = '-'
# BlinkCmpKindReference = '-'
# BlinkCmpKindFolder = '-'
# BlinkCmpKindEnumMember = '-'
# BlinkCmpKindConstant = '-'
# BlinkCmpKindStruct = '-'
# BlinkCmpKindEvent = '-'
# BlinkCmpKindOperator = '-'
# BlinkCmpKindTypeParameter = '-'
